# Generated by Django 3.0.4 on 2020-06-04 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='static/media/profile')),
                ('selfDescription', models.TextField(blank=True)),
                ('DateOfBirth', models.DateField(blank=True, default=datetime.datetime.today)),
                ('gender', models.CharField(blank=True, choices=[('ml', 'male'), ('fml', 'female'), ('oth', 'other')], max_length=3)),
                ('isAnonymousQuestionsAllowed', models.BooleanField(default=True)),
                ('isUserAnswersVisibleInFeed', models.BooleanField(default=True)),
                ('friends', models.ManyToManyField(related_name='_myuser_friends_+', to='mainapp.MyUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='static/media/temp')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question')),
            ],
        ),
    ]
