# Generated by Django 3.0.4 on 2020-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200604_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_myuser_friends_+', to='mainapp.MyUser'),
        ),
    ]
