# Generated by Django 3.0.4 on 2020-06-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200604_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='friends',
        ),
    ]
