# Generated by Django 3.0.4 on 2020-06-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_myuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='askedUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='askedUser', to='mainapp.MyUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asker', to='mainapp.MyUser'),
        ),
    ]
