# Generated by Django 3.0.4 on 2020-06-22 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200622_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 7, 48, 21, 582607, tzinfo=utc)),
        ),
    ]
