# Generated by Django 3.0.4 on 2020-06-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200622_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
